### ISSUE TITLE
calendar view error

### ISSUE THREAD

**Issue by kyunghoj** [alexras/markupserve#4]
I tried to use the calendar view, but it didn't work. The following is the error message:

```
$ ./markupserve.py 
Loading index at '/home/kyunghoj/.markupserve_index'
Bottle v0.12.8 server starting up (using PasteServer())...
Listening on http://localhost:8080/
Hit Ctrl-C to quit.

serving on http://127.0.0.1:8080
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "./markupserve.py", line 401, in view_index
    return view("/")
  File "./markupserve.py", line 391, in view
    dir_config)
  File "./markupserve.py", line 161, in view_calendar
    parent_path = file_path_to_server_path(parent_path, root))
  File "./markupserve.py", line 76, in file_path_to_server_path
    return os.path.join("/view", os.path.relpath(path, root))
  File "/usr/lib/python2.7/posixpath.py", line 435, in relpath
    raise ValueError("no path specified")
ValueError: no path specified
127.0.0.1 - - [14/Apr/2015:12:23:08 -0400] "GET / HTTP/1.1" 500 1768 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
```

This is my `config.cfg`.

```
[markupserve]
document_root = ~/Dropbox/Research/Notebooks
#document_root = ~/Documents
port=8080
converter_binary = ./renderer.py
markup_suffixes = .md, .text, .mkd, .markdown
index_root = ~/.markupserve_index
```

And `.markupserve_dir_config`

```
[style]
name: calendar
file_prefix: "journal-"
file_suffix: ".markdown"
```

The directory is like this:

```
$ ls -al
total 80
drwxr-xr-x  2 kyunghoj csgrad  4096 Apr 14 11:38 .
drwxr-xr-x 22 kyunghoj csgrad  4096 Apr 13 16:13 ..
-rw-r--r--  1 kyunghoj csgrad     0 Apr 14 10:47 journal-2015-03-01.markdown
-rw-r--r--  1 kyunghoj csgrad  2519 Apr  9 09:53 journal-2015-04-05.markdown
-rw-r--r--  1 kyunghoj csgrad  2686 Apr 14 10:34 journal-2015-04-13.markdown
-rw-r--r--  1 kyunghoj csgrad    22 Apr 14 11:34 journal-2015-04-14.markdown
-rw-r--r--  1 kyunghoj csgrad    72 Apr 14 10:37 .markupserve_dir_config
-rw-r--r--  1 kyunghoj csgrad 22933 Apr  5 23:42 notebook.markdown
```

The following is my environment:

```
$ uname -a
Linux staten 3.13.0-49-generic #81-Ubuntu SMP Tue Mar 24 19:29:48 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```

I tried to fix the code, but what I could do is only the following workaround:

```
$ git diff markupserve.py 
diff --git a/markupserve.py b/markupserve.py
index 0028e84..ebcd622 100755
--- a/markupserve.py
+++ b/markupserve.py
@@ -73,6 +73,8 @@ def last_modified_string(file_path):
             os.path.getmtime(file_path)))
 
 def file_path_to_server_path(path, root):
+    if path is None:
+        return
     return os.path.join("/view", os.path.relpath(path, root))
 
 def view_calendar(path, parent_path, root, config):
```

**Comment by alexras** [comment]
Thanks for reporting this, and sorry about the delay getting it closed.
